/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddListItem: typeof import('./components/AddListItem.vue')['default']
    ListItem: typeof import('./components/ListItem.vue')['default']
    Login: typeof import('./components/Login.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Share: typeof import('./components/Share.vue')['default']
    ShoppingList: typeof import('./components/ShoppingList.vue')['default']
    Toolbar: typeof import('./components/Toolbar.vue')['default']
    TotalCost: typeof import('./components/TotalCost.vue')['default']
  }
}
